### ISSUE TITLE
Feature request: a new function or a new package for numbering math equations

### ISSUE THREAD

**Issue by OrangeX4** [RubixDev/typst-i-figured#1]
There is currently no package available for numbering math equations, so I made a simple modification to your i-figured package source code to create a basic equation numbering package. Since most of the code is still yours, I believe it should be up to you to add or release a new package.

Best wishes :-)

```typst
Numbered @eqt:ratio:

$ phi.alt := (1 + sqrt(5)) / 2 $ <ratio>

Numbered with `only-labeled: false`:

$ phi.alt := (1 + sqrt(5)) / 2 $

Unnumbered with `only-labeled: true`:

$ phi.alt := (1 + sqrt(5)) / 2 $

Unnumbered with `<->`:

$ phi.alt := (1 + sqrt(5)) / 2 $ <->
```

```typst
#let reset-counters(it, level: 1) = {
  if it.level <= level {
    counter(math.equation).update(0)
  }
  it
}

#let _typst-numbering = numbering
#let show-equation(
  it,
  level: 1,
  zero-fill: true,
  leading-zero: true,
  numbering: "(1.1)",
  prefix: "eqt:",
  only-labeled: false,
  unnumbered-label: "-",
) = {
  if (only-labeled and "label" not in it.fields()) {
    it
  } else if "label" in it.fields() and (str(it.label).starts-with(prefix) or str(it.label) == unnumbered-label) {
    it
  } else {
    let numbers = counter(heading).at(it.location())
    // if zero-fill is true add trailing zeros until the level is reached
    while zero-fill and numbers.len() < level { numbers.push(0) }
    // only take the first `level` numbers
    if numbers.len() > level { numbers = numbers.slice(0, level) }
    // strip a leading zero if requested
    if not leading-zero and numbers.at(0, default: none) == 0 {
      numbers = numbers.slice(1)
    }

    let dic = it.fields()
    let _ = if "body" in dic { dic.remove("body") }
    let _ = if "label" in dic { dic.remove("label") }
    let _ = if "counter" in dic { dic.remove("counter") }

    let equation = math.equation(
      it.body,
      ..dic,
      numbering: n => _typst-numbering(numbering, ..numbers, n),
    )
    if it.has("label") {
      let new-label = label(prefix + str(it.label))
      [#equation #new-label]
    } else {
      let new-label = label(prefix + "no-label")
      [#equation #new-label]
    }
  }
}
```

**Comment by OrangeX4** [comment]
I didn't get a reply for a long time, so I created a package: https://github.com/typst/packages/pull/212

Closed this issue :-)

**Comment by RubixDev** [comment]
Sorry, I'm currently on vacation and will be for another 1.5 weeks. I think the idea is good and i would love to add it to this package. I just didn't have time to do that yet. (btw, four days isn't a long time :wink:)

**Comment by OrangeX4** [comment]
Oh, I'm sorry, I didn't wait for a reply.

So I made a PR to the typst package to add the i-equation package and added you to the authors of the package. Would you like to have a new package `i-equation` or do you want to add equation numbering to the i-figured (so the package name might be a bit misleading)? If it's the latter, I'll withdraw the PR in the typst package.

Best wishes, have a great vacation :-)

**Comment by RubixDev** [comment]
Thank you for your patience! I finally got around to adding this. The open packages PR is here: https://github.com/typst/packages/pull/240

**Comment by OrangeX4** [comment]
Great, thank you for liking it, and I'm glad to see that the code was added to i-figured. 😉
