### ISSUE TITLE
[Feature required] support for https://typst.app/universe/package/lovelace

### ISSUE THREAD

**Issue by Lucas-Wye** [RubixDev/typst-i-figured#11]
https://typst.app/universe/package/lovelace is used as the algorithm package in LaTeX, could you provide a similar behavior?

For example, **Algo. 2.1** (section.subsection).

**Comment by RubixDev** [comment]
Am I missing something? As far as I can tell, this already works. The "basic" i-figured example already shows how to use it with a custom "atom" figure kind, and the lovelace docs explain how to use it with figures. Combining the two is trivial:

```typ
#import "@preview/i-figured:0.2.4"
#import "@preview/lovelace:0.3.0"

#set heading(numbering: "1.")

#show heading: i-figured.reset-counters.with(extra-kinds: ("algorithm",))
#show figure: i-figured.show-figure.with(extra-prefixes: (algorithm: "alg:"))

#show figure.where(kind: "algorithm"): set figure(supplement: [Algo])

#i-figured.outline(target-kind: "algorithm", title: [List of Algorithms])
```

https://typst.app/project/rpvDfN-NvOIr92vlmO727f

**Comment by Lucas-Wye** [comment]
> Am I missing something? As far as I can tell, this already works. The "basic" i-figured example already shows how to use it with a custom "atom" figure kind, and the lovelace docs explain how to use it with figures. Combining the two is trivial:
> 
> ```typst
> #import "@preview/i-figured:0.2.4"
> #import "@preview/lovelace:0.3.0"
> 
> #set heading(numbering: "1.")
> 
> #show heading: i-figured.reset-counters.with(extra-kinds: ("algorithm",))
> #show figure: i-figured.show-figure.with(extra-prefixes: (algorithm: "alg:"))
> 
> #show figure.where(kind: "algorithm"): set figure(supplement: [Algo])
> 
> #i-figured.outline(target-kind: "algorithm", title: [List of Algorithms])
> ```
> 
> https://typst.app/project/rpvDfN-NvOIr92vlmO727f

It works.

thx a lot!
