### ISSUE TITLE
Exclude inline equations for numbering

### ISSUE THREAD

**Issue by tobiasforest** [RubixDev/typst-i-figured#4]
When I enabled i-figured using
```typ
#show math.equation: i-figured.show-equation
```

and when I type
```typ
$a$, $b$, $c$, $d$, $e$, $f$, $g$, $h$
```

it shows:
<img width="169" alt="image" src="https://github.com/RubixDev/typst-i-figured/assets/59563695/f7504d00-4dec-40fc-a9de-0081c5fbd0bb">

with an unexpected space after each inline math expression. 

However, it should be like this:
<img width="130" alt="image" src="https://github.com/RubixDev/typst-i-figured/assets/59563695/40c129da-284c-4831-9493-00a6c1668dae">

The solution is to add a `where` to `show`, since we do not need to number inline math expressions:

```typ
#show math.equation.where(block: true): i-figured.show-equation
```

Since I entered the initial commands as per the examples, maybe you could adjust them. Thanks a lot!

**Comment by RubixDev** [comment]
Since inline equations should never be affected, I made it so they are ignored even with
```typ
#show math.equation: i-figured.show-equation
```
