### ISSUE TITLE
[Feature request] Add Table counter

### ISSUE THREAD

**Issue by roaldarbol** [RubixDev/typst-i-figured#9]
Hi there! Thanks for making this wonderful extension - it's making life easier! As it also supports equations, I'm wondering if it could also support tables? The use-case is exactly the same. :-)
Cheers!

**Comment by RubixDev** [comment]
The main example right at the start of the [package site](https://typst.app/universe/package/i-figured) shows that it can be used with figures, tables, listings, equations, and even custom figure kinds. The relevant code is https://github.com/RubixDev/typst-i-figured/blob/36e238538142ed123d6493a49d756088587d075b/examples/basic.typ#L17-L23 and https://github.com/RubixDev/typst-i-figured/blob/36e238538142ed123d6493a49d756088587d075b/examples/basic.typ#L29-L37

**Comment by roaldarbol** [comment]
Ah, that's my bad, thanks! Have to get used to the "everything is a figure" syntax of Typst. ;-)
